// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("EH OH JE SUIS LA GROS TAS");
    println!("cargo:rerun-if-changed=migrations");
}
