-- Add migration script here

ALTER TABLE users
ADD COLUMN guild_id varchar(20) UNIQUE NOT NULL DEFAULT '138324375639293953';

ALTER TABLE users ADD CONSTRAINT guilds_fk FOREIGN KEY (guild_id)
REFERENCES guilds (guild_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE users ALTER COLUMN guild_id DROP DEFAULT;
